name: github_issue_list
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  logger: ^1.3.0
  flutter_screenutil: ^5.5.3+2
  dio: ^5.1.1

#  dio_http_formatter: ^2.1.0
  dio_cache_interceptor: ^3.3.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.11
  dio_cache_interceptor_hive_store: ^3.2.0
  connectivity_plus: ^3.0.6
  get_storage: ^2.1.1
  pull_to_refresh: #^2.0.0
    git:
      url: https://github.com/ymback/flutter_pulltorefresh.git
  google_fonts: ^4.0.4
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

